--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iiFlamiinBlaze/PocketMine-Plugins
branches:
- master
projects:
  AdvancedFly:
    path: AdvancedFly/
  AdvancedFeed:
    path: AdvancedFeed/
  AdvancedJoin:
    path: AdvancedJoin/
...